version: '2.1'

services:

  mailparser:
    image: fmantuano/spamscope-mail-parser:develop
    command: --json -f /mails/mail_test_1
    container_name: composer_mailparser
    volumes:
      - ~/mails/:/mails/:ro
